spring.application.name=gestionguias

spring.datasource.url=jdbc:postgresql://localhost:5432/gestionguias
spring.datasource.username=postgres
spring.datasource.password=2785030Cp

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true